export const people = [
    {name: "MIKE", id: 0, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortFlat&accessoriesType=Prescription02&hairColor=Black&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Blue01&eyeType=Squint&eyebrowType=SadConcernedNatural&mouthType=Smile&skinColor=Light'},
    {name: "SALLY", id: 1, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=LongHairStraightStrand&accessoriesType=Blank&hairColor=BlondeGolden&facialHairType=Blank&clotheType=Hoodie&clotheColor=White&eyeType=Default&eyebrowType=UpDownNatural&mouthType=Serious&skinColor=Pale'},
    {name: "DAISY", id: 2, image: "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairCurvy&accessoriesType=Prescription01&hairColor=BrownDark&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Happy&eyebrowType=Default&mouthType=Twinkle&skinColor=Light"},
    {name: "JOHNSON", id: 3, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Brown&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Side&eyebrowType=UpDown&mouthType=Serious&skinColor=Brown'},
    {name: "TYSON", id: 4, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairDreads01&accessoriesType=Wayfarers&hairColor=BrownDark&facialHairType=BeardLight&facialHairColor=Brown&clotheType=ShirtCrewNeck&clotheColor=Black&eyeType=Wink&eyebrowType=UpDown&mouthType=Default&skinColor=DarkBrown'},
    {name: "ALI", id: 5, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=NoHair&accessoriesType=Blank&facialHairType=BeardMajestic&facialHairColor=Black&clotheType=BlazerSweater&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=Light'},
    {name: "TUCKER", id: 6, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairDreads01&accessoriesType=Blank&hairColor=Black&facialHairType=BeardLight&facialHairColor=Black&clotheType=CollarSweater&clotheColor=PastelGreen&eyeType=Squint&eyebrowType=UpDown&mouthType=Twinkle&skinColor=Light'},
    {name: "SUZY", id: 7, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=LongHairBigHair&accessoriesType=Blank&hairColor=Brown&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Pink&eyeType=Default&eyebrowType=RaisedExcitedNatural&mouthType=Default&skinColor=Pale'},
    {name: "ABRAHAM", id: 8, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=BeardLight&facialHairColor=Black&clotheType=Hoodie&clotheColor=Gray01&eyeType=Default&eyebrowType=Default&mouthType=Disbelief&skinColor=Brown'},
    {name: "JOSEPH", id: 9, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShaggyMullet&accessoriesType=Prescription02&hairColor=Brown&facialHairType=BeardLight&facialHairColor=Brown&clotheType=CollarSweater&clotheColor=Heather&eyeType=Happy&eyebrowType=RaisedExcited&mouthType=Default&skinColor=Light'},
    {name: "MOLLY", id: 10, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=LongHairMiaWallace&accessoriesType=Round&hairColor=Red&facialHairType=Blank&clotheType=CollarSweater&clotheColor=PastelYellow&eyeType=Default&eyebrowType=RaisedExcitedNatural&mouthType=Concerned&skinColor=Brown'},
    {name: "MIA", id: 11, image: 'https://avataaars.io/?avatarStyle=Transparent&topType=LongHairBob&accessoriesType=Blank&hairColor=Red&facialHairType=Blank&clotheType=ShirtCrewNeck&clotheColor=Red&eyeType=Side&eyebrowType=RaisedExcitedNatural&mouthType=Twinkle&skinColor=Light'}
]